import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "donebyhd",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className="no-scrollbar scroll-smooth"
			suppressHydrationWarning
		>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
